//A function to ask the user if they would like to play the game
var counter = 0;

playTheGame();

function playTheGame()
{
    let userSelection = confirm("Would you like to play the game?");
    let userNumber;
    let computerNumber;

    if(userSelection == false)
    {
        alert('No problem, Goodbye');
    }
    else
    {
        // Ask the user to enter a number
        userNumber = Number(prompt("Enter a number between 0 and 10"));

        if(isNaN(userNumber))
        {
            alert('Sorry Not a number, Goodbye');
            playTheGame();
        }
        else if(userNumber < 0 || userNumber > 10)
        {
            alert('Sorry it’s not a good number, Goodbye');
            playTheGame();
        }
        else
        {
            computerNumber = Math.round(Math.random() * 10); //A random number is generated by the computer.
            console.log(computerNumber);
            compareNumbers(userNumber,computerNumber);
        }        
    }
}
function compareNumbers(userNumber,computerNumber) 
{
    counter++;
    console.log(counter);
    if(counter > 3)
    {
        alert('Out of Chances!!!')
        return;
    }
    if(userNumber == computerNumber)
    {
        alert("WINNER")
        return; // stops the function
    }
    else if(userNumber > computerNumber)
    {
        alert("Your number is bigger then the computer’s, guess again");
        userNumber = prompt("Enter a new number");
        compareNumbers(userNumber,computerNumber);
    }
    else if(userNumber < computerNumber)
    {
        alert("Your number is smaller then the computer’s, guess again");
        userNumber = prompt("Enter a new number");
        compareNumbers(userNumber,computerNumber);
    }
}
